version: "3.8"
services:
  platform:
    image: platform
    build:
      context: platform/.
      dockerfile: Dockerfile
    ports:
    - 80:80
    env_file:
      - .env
  worker:
    image: worker
    build:
      context: worker/.
      dockerfile: Dockerfile
    env_file:
      - .env